# Generated by Django 4.1.3 on 2022-11-12 16:17

import destination.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('summary', models.TextField(max_length=1000)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to=destination.models.destination_image_upload)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
