# Generated by Django 4.1.3 on 2022-11-13 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0003_event_slug_site_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='owner',
        ),
    ]
