# Generated by Django 4.1.3 on 2022-11-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0004_remove_comment_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
