# Generated by Django 4.1.3 on 2022-11-16 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0006_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='map_link',
            field=models.URLField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
