# Generated by Django 4.1.3 on 2022-11-16 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0007_site_map_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='published_at',
            field=models.DateTimeField(),
        ),
    ]
